const btn1 = document.getElementById('btn-1');
const btn2 = document.getElementById('btn-2');
const btn3 = document.getElementById('btn-3');
const btn4 = document.getElementById('btn-4');
const btn5 = document.getElementById('btn-5');
const btn6 = document.getElementById('btn-6');

const pag1 = document.getElementById('view1');
const pag2 = document.getElementById('view2');
const pag3 = document.getElementById('view3');
const pag4 = document.getElementById('view4');
const pag5 = document.getElementById('view5');
const pag6 = document.getElementById('view6');

btn1.addEventListener('click', () => {
    pag2.style.display = 'none';
    pag1.style.display = 'flex';
    pag3.style.display = 'none';
    pag4.style.display = 'none';
    pag5.style.display = 'none';
    pag6.style.display = 'none';
    btn1.style.background = 'red';
    btn1.style.color = 'white';
    btn2.style.background = 'rgb(197, 197, 197)';
    btn2.style.color = 'black';
    btn3.style.background = 'rgb(197, 197, 197)';
    btn3.style.color = 'black';
    btn4.style.background = 'rgb(197, 197, 197)';
    btn4.style.color = 'black';
    btn5.style.background = 'rgb(197, 197, 197)';
    btn5.style.color = 'black';
    btn6.style.background = 'rgb(197, 197, 197)';
    btn6.style.color = 'black';
});

btn2.addEventListener('click', () => {
    pag2.style.display = 'flex';
    pag1.style.display = 'none';
    pag3.style.display = 'none';
    pag4.style.display = 'none';
    pag5.style.display = 'none';
    pag6.style.display = 'none';
    btn2.style.background = 'red';
    btn2.style.color = 'white';
    btn1.style.background = 'rgb(197, 197, 197)';
    btn1.style.color = 'black';
    btn3.style.background = '';
    btn3.style.color = 'black';
    btn4.style.background = '';
    btn4.style.color = 'black';
    btn5.style.background = '';
    btn5.style.color = 'black';
    btn6.style.background = '';
    btn6.style.color = 'black';
});

btn3.addEventListener('click', () => {
    pag2.style.display = 'none';
    pag1.style.display = 'none';
    pag3.style.display = 'flex';
    pag4.style.display = 'none';
    pag5.style.display = 'none';
    pag6.style.display = 'none';
    btn3.style.background = 'red';
    btn3.style.color = 'white';
    btn2.style.background = '';
    btn2.style.color = 'black';
    btn1.style.background = 'rgb(197, 197, 197)';
    btn1.style.color = 'black';
    btn4.style.background = '';
    btn4.style.color = 'black';
    btn5.style.background = '';
    btn5.style.color = 'black';
    btn6.style.background = '';
    btn6.style.color = 'black';
});

btn4.addEventListener('click', () => {
    pag2.style.display = 'none';
    pag1.style.display = 'none';
    pag3.style.display = 'none';
    pag4.style.display = 'flex';
    pag5.style.display = 'none';
    pag6.style.display = 'none';
    btn4.style.background = 'red';
    btn4.style.color = 'white';
    btn2.style.background = '';
    btn2.style.color = 'black';
    btn3.style.background = '';
    btn3.style.color = 'black';
    btn1.style.background = 'rgb(197, 197, 197)';
    btn1.style.color = 'black';
    btn5.style.background = '';
    btn5.style.color = 'black';
    btn6.style.background = '';
    btn6.style.color = 'black';
});

btn5.addEventListener('click', () => {
    pag2.style.display = 'none';
    pag1.style.display = 'none';
    pag3.style.display = 'none';
    pag4.style.display = 'none';
    pag5.style.display = 'flex';
    pag6.style.display = 'none';
    btn5.style.background = 'red';
    btn5.style.color = 'white';
    btn2.style.background = '';
    btn2.style.color = 'black';
    btn3.style.background = '';
    btn3.style.color = 'black';
    btn4.style.background = '';
    btn4.style.color = 'black';
    btn1.style.background = 'rgb(197, 197, 197)';
    btn1.style.color = 'black';
    btn6.style.background = '';
    btn6.style.color = 'black';
});

btn6.addEventListener('click', () => {
    pag2.style.display = 'none';
    pag1.style.display = 'none';
    pag3.style.display = 'none';
    pag4.style.display = 'none';
    pag5.style.display = 'none';
    pag6.style.display = 'flex';
    btn6.style.background = 'red';
    btn6.style.color = 'white';
    btn2.style.background = '';
    btn2.style.color = 'black';
    btn3.style.background = '';
    btn3.style.color = 'black';
    btn4.style.background = '';
    btn4.style.color = 'black';
    btn5.style.background = '';
    btn5.style.color = 'black';
    btn1.style.background = 'rgb(197, 197, 197)';
    btn1.style.color = 'black';
});